version: "3.9"
services:

  db:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: mudar123
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
  web:
    build: ./api/
    depends_on:
      - db
    ports:
      - 8080:8080
